import "./globals.css";
export const metadata = {
  title: "Adult",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      <body>
        {children}
      </body>
    </html>
  );
}
